### ISSUE TITLE
用两天网速就特别慢！

### ISSUE THREAD

**Issue by limintao** [wulabing/Xray_onekey#253]
刚安装的网速非常好，4K无压力，但是过两天就没什么网速了，打开个网页都要半天，请教一下这是什么原因引起的？

**Comment by yuleeee** [comment]
我也发现了这个问题，我回到服务器一看，发现占用内存会随着时间越来越多。
而且网速也会随着内存的增大而越来越慢。
我想搞清楚这个‘内存占用越来越多’的问题，应该就能解决网速变慢的问题

**Comment by Gslw** [comment]
同样的问题，油管降速很明显

**Comment by zclsaber** [comment]
我刚装好，速度现在就很慢，和虚拟机的选区有关系吗？

**Comment by MichaelVector** [comment]
同问，我也有这样的问题

**Comment by Blink1024** [comment]
我这里是NetworkManager内存占用不断增大
设置个定时任务吧,定时重启一下
systemctl restart NetworkManager

**Comment by NetHeritage** [comment]
慢与脚本关系不大吧，，，

**Comment by XgHao** [comment]
`* */1 * * * /sbin/reboot`
每小时重启一次服务器就行了  稳如老狗

**Comment by PoorerImmune** [comment]
這不是機器的問題，我看很多人在這裡反映該作者的程式執行起來確實會導致 URL 的解析速度慢。我裝了之後也是肉眼感知到解析太慢，要等 5 秒以上才能把頁面載入出來，而且該程式已經嚴重影響到國內 URL 的解析速度。

**Comment by MichaelVector** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你所发的邮件我以收到。我将在工作结束后，尽快给您回复。

**Comment by KukiSa** [comment]
@PoorerImmune Regarding the response time of DNS resolution requests, it is recommended that you adjust the DNS offload settings of the client. For the delay caused by the need to transmit through the intermediate layer such as WebSocket, Nginx and CDN in the process of sending the DNS resolution request to the remote server, it is recommended that you reduce the intermediate layer, or purchase a server optimized for the direction of mainland China.
