### ISSUE TITLE
安装失败：提示chrony 时间同步服务  失败。不知道怎么解决

### ISSUE THREAD

**Issue by GuoZhiQiang** [wulabing/Xray_onekey#265]
当前已安装版本:None

—————————————— 安装向导 ——————————————
0.  升级 脚本
1.  安装 V2Ray (Nginx+ws+tls)
2.  安装 V2Ray (http/2)
3.  升级 V2Ray core
—————————————— 配置变更 ——————————————
4.  变更 UUID
5.  变更 alterid
6.  变更 port
7.  变更 TLS 版本(仅ws+tls有效)
—————————————— 查看信息 ——————————————
8.  查看 实时访问日志
9.  查看 实时错误日志
10. 查看 V2Ray 配置信息
—————————————— 其他选项 ——————————————
11. 安装 4合1 bbr 锐速安装脚本
12. 安装 MTproxy(支持TLS混淆)
13. 证书 有效期更新
14. 卸载 V2Ray
15. 更新 证书crontab计划任务
16. 清空 证书遗留文件
17. 退出 

请输入数字：1
[OK]  当前用户是root用户，进入安装流程 
[OK]  当前系统为 Debian 9 stretch 
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://ftp.debian.org/debian stretch InRelease                                
Hit:3 http://ftp.debian.org/debian stretch-updates InRelease
Hit:4 http://ftp.debian.org/debian stretch Release 
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
145 packages can be upgraded. Run 'apt list --upgradable' to see them.
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
Failed to stop firewalld.service: Unit firewalld.service not loaded.
Failed to disable unit: No such file or directory
[OK]  firewalld 已关闭 
Failed to stop ufw.service: Unit ufw.service not loaded.
Failed to disable unit: No such file or directory
[OK]  ufw 已关闭 
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
[错误]  安装 chrony 时间同步服务  失败

**Comment by GuoZhiQiang** [comment]
解决了删除lock文件：  rm /var/cache/apt/archives/lock

**Comment by GuoZhiQiang** [comment]
解决了删除lock文件：  

1. `rm /var/cache/apt/archives/lock`
2. `rm /var/lib/dpkg/lock`

**Comment by JameryP** [comment]
我也遇到了这个，但是你的方法我试了，不管用
Setting up chrony (3.0-4+deb9u2) ...
Job for chrony.service failed because the control process exited with error code.
See "systemctl status chrony.service" and "journalctl -xe" for details.
invoke-rc.d: initscript chrony, action "start" failed.
¡ñ chrony.service - chrony, an NTP client/server
   Loaded: loaded (/lib/systemd/system/chrony.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-10-15 17:03:02 CEST; 34ms ago
     Docs: man:chronyd(8)
           man:chronyc(1)
           man:chrony.conf(5)
  Process: 7324 ExecStart=/usr/sbin/chronyd (code=exited, status=1/FAILURE)

Oct 15 17:03:01 srv16199 systemd[1]: chrony.service: Failed to reset devices.list: Operation not permitted
Oct 15 17:03:01 srv16199 systemd[1]: chrony.service: Failed to set invocation ID on control group /system.slice/chrony.serv¡­permitted
Oct 15 17:03:01 srv16199 systemd[1]: Starting chrony, an NTP client/server...
Oct 15 17:03:01 srv16199 chronyd[7324]: adjtimex(0x8001) failed : Operation not permitted
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package chrony (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 chrony
